apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
    version: "1"
    color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: "1"
  template:
    metadata:
      labels:
        app: myapp
        version: "1"
        color: blue
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        env:
        - name: COLOR
          value: "BLUE"
        command: ["/bin/sh","-c"]
        args:
        - |
          echo "<html><body style='background-color:lightblue;text-align:center;font-family:sans-serif;'>
          <h1 style='color:navy;'>💙 BLUE version</h1>
          <p>This is the blue deployment of myapp.</p>
          </body></html>" > /usr/share/nginx/html/index.html && exec nginx -g 'daemon off;'
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green
  labels:
    app: myapp
    version: "2"
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: "2"
  template:
    metadata:
      labels:
        app: myapp
        version: "2"
        color: green
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        env:
        - name: COLOR
          value: "GREEN"
        command: ["/bin/sh","-c"]
        args:
        - |
          echo "<html><body style='background-color:lightgreen;text-align:center;font-family:sans-serif;'>
          <h1 style='color:darkgreen;'>💚 GREEN version</h1>
          <p>This is the green deployment of myapp.</p>
          </body></html>" > /usr/share/nginx/html/index.html && exec nginx -g 'daemon off;'
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
spec:
  type: ClusterIP
  selector:
    app: myapp
    color: blue   # 👈 switch this between blue and green
  ports:
  - port: 80
    targetPort: 80
