apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "diner.fullname" . }}-green
  labels:
    app.kubernetes.io/name: {{ include "diner.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    color: green
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "diner.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      color: green
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "diner.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        color: green
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: html
          configMap:
            name: {{ include "diner.fullname" . }}-green-index
