apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "diner.fullname" . }}-ing
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "diner.fullname" . }}-svc
                port:
                  number: 80
