apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diner-stable
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: diner-lab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: diner-stable
            port:
              number: 80
